
* 2025
** 2025-02 February
*** 2025-02-08 Saturday
**** [2025-02-08 Sat 21:14] Feeling prett good about things

Wow -- the last several days have been an abosolute blur. I really went all in wrt to getting my development environment setup how I wanted... specifically, I nuked my laptop and re-installed my entire system as declaratively as possible using nix-darwin. What was especially cool about that was that I am also specifyin all of my homebrew packages this way too... which I love and it gives me ample flexibility of brew while also managing to be quite declarative.

Then, I went through the struggle bus with getting emacs installed and configured (which was its own bear). Finally, I got the debugger system working which was a massive pain the ass... basically the regular DAP debugger sucked and I swapped to one called DAPE and that seems to work for everything (python, C/++, typescript) so far... though I have not quite gotten the full hang of it.


There are a couple of random "TODO" items I want to ensure... like code linting for typescript projects (which bit me in the ass with Hadrian a few months ago).
Anyway, now that things are nearly fully configured, I can finally really lean back into coding practice with C/C++ and cracking the coding interview type stuff.

That'll be a couple of weeks of work no doubt, but I suspect it'll be worth it. I can probably "safely" cover my ass for another month, but I really want to get a regular job again soon (or work on a startup that gives me a paycheck).
Anyway, there are, as always endless projects and project ideas... I will start trying to use org mode as often as I can for tracking and managing them... still have to do a bit of learning and setup... but that will be organizational instead of functional.

I think that's it for now. Will try to also get Yabai re-installed on my machine as I loved that program and its i3-esque functionality...

Ok, to specify the TODO items I need to add

- Installing Yabai
- Ensure code linting works wrt style guides (see Hadrian project)
- Re-install Yabai window manager (keeping SIPS enabled I think...)
- Look into publishing a blog

That last point is something Alessandra pointed out. Basically, I havel learned a lot of great stuff ( my current system configuration, for example or yabai or debuggers ) and it would maybe be beneficial for someone else in the future to be able to find and replicate that kind of thing. I'll give it some thought. OK over and out
